/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StartRouteImport } from './routes/start'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDoctorRouteImport } from './routes/_authenticated/doctor'
import { Route as AuthenticatedReviewIdRouteImport } from './routes/_authenticated/review.$id'
import { Route as AuthenticatedPaymentIdRouteImport } from './routes/_authenticated/payment.$id'
import { Route as AuthenticatedIntakeIdRouteImport } from './routes/_authenticated/intake.$id'
import { Route as AuthenticatedDoctorsIdRouteImport } from './routes/_authenticated/doctors.$id'
import { Route as AuthenticatedConsultationIdRouteImport } from './routes/_authenticated/consultation.$id'
import { Route as AuthenticatedDoctorCaseIdRouteImport } from './routes/_authenticated/doctor.case.$id'

const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDoctorRoute = AuthenticatedDoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReviewIdRoute = AuthenticatedReviewIdRouteImport.update({
  id: '/review/$id',
  path: '/review/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPaymentIdRoute = AuthenticatedPaymentIdRouteImport.update({
  id: '/payment/$id',
  path: '/payment/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntakeIdRoute = AuthenticatedIntakeIdRouteImport.update({
  id: '/intake/$id',
  path: '/intake/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDoctorsIdRoute = AuthenticatedDoctorsIdRouteImport.update({
  id: '/doctors/$id',
  path: '/doctors/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConsultationIdRoute =
  AuthenticatedConsultationIdRouteImport.update({
    id: '/consultation/$id',
    path: '/consultation/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDoctorCaseIdRoute =
  AuthenticatedDoctorCaseIdRouteImport.update({
    id: '/case/$id',
    path: '/case/$id',
    getParentRoute: () => AuthenticatedDoctorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/start': typeof StartRoute
  '/doctor': typeof AuthenticatedDoctorRouteWithChildren
  '/history': typeof AuthenticatedHistoryRoute
  '/api/chat': typeof ApiChatRoute
  '/consultation/$id': typeof AuthenticatedConsultationIdRoute
  '/doctors/$id': typeof AuthenticatedDoctorsIdRoute
  '/intake/$id': typeof AuthenticatedIntakeIdRoute
  '/payment/$id': typeof AuthenticatedPaymentIdRoute
  '/review/$id': typeof AuthenticatedReviewIdRoute
  '/doctor/case/$id': typeof AuthenticatedDoctorCaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/start': typeof StartRoute
  '/doctor': typeof AuthenticatedDoctorRouteWithChildren
  '/history': typeof AuthenticatedHistoryRoute
  '/api/chat': typeof ApiChatRoute
  '/consultation/$id': typeof AuthenticatedConsultationIdRoute
  '/doctors/$id': typeof AuthenticatedDoctorsIdRoute
  '/intake/$id': typeof AuthenticatedIntakeIdRoute
  '/payment/$id': typeof AuthenticatedPaymentIdRoute
  '/review/$id': typeof AuthenticatedReviewIdRoute
  '/doctor/case/$id': typeof AuthenticatedDoctorCaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/start': typeof StartRoute
  '/_authenticated/doctor': typeof AuthenticatedDoctorRouteWithChildren
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/consultation/$id': typeof AuthenticatedConsultationIdRoute
  '/_authenticated/doctors/$id': typeof AuthenticatedDoctorsIdRoute
  '/_authenticated/intake/$id': typeof AuthenticatedIntakeIdRoute
  '/_authenticated/payment/$id': typeof AuthenticatedPaymentIdRoute
  '/_authenticated/review/$id': typeof AuthenticatedReviewIdRoute
  '/_authenticated/doctor/case/$id': typeof AuthenticatedDoctorCaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/start'
    | '/doctor'
    | '/history'
    | '/api/chat'
    | '/consultation/$id'
    | '/doctors/$id'
    | '/intake/$id'
    | '/payment/$id'
    | '/review/$id'
    | '/doctor/case/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/start'
    | '/doctor'
    | '/history'
    | '/api/chat'
    | '/consultation/$id'
    | '/doctors/$id'
    | '/intake/$id'
    | '/payment/$id'
    | '/review/$id'
    | '/doctor/case/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/start'
    | '/_authenticated/doctor'
    | '/_authenticated/history'
    | '/api/chat'
    | '/_authenticated/consultation/$id'
    | '/_authenticated/doctors/$id'
    | '/_authenticated/intake/$id'
    | '/_authenticated/payment/$id'
    | '/_authenticated/review/$id'
    | '/_authenticated/doctor/case/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  StartRoute: typeof StartRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/doctor': {
      id: '/_authenticated/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof AuthenticatedDoctorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/review/$id': {
      id: '/_authenticated/review/$id'
      path: '/review/$id'
      fullPath: '/review/$id'
      preLoaderRoute: typeof AuthenticatedReviewIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payment/$id': {
      id: '/_authenticated/payment/$id'
      path: '/payment/$id'
      fullPath: '/payment/$id'
      preLoaderRoute: typeof AuthenticatedPaymentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/intake/$id': {
      id: '/_authenticated/intake/$id'
      path: '/intake/$id'
      fullPath: '/intake/$id'
      preLoaderRoute: typeof AuthenticatedIntakeIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/doctors/$id': {
      id: '/_authenticated/doctors/$id'
      path: '/doctors/$id'
      fullPath: '/doctors/$id'
      preLoaderRoute: typeof AuthenticatedDoctorsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/consultation/$id': {
      id: '/_authenticated/consultation/$id'
      path: '/consultation/$id'
      fullPath: '/consultation/$id'
      preLoaderRoute: typeof AuthenticatedConsultationIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/doctor/case/$id': {
      id: '/_authenticated/doctor/case/$id'
      path: '/case/$id'
      fullPath: '/doctor/case/$id'
      preLoaderRoute: typeof AuthenticatedDoctorCaseIdRouteImport
      parentRoute: typeof AuthenticatedDoctorRoute
    }
  }
}

interface AuthenticatedDoctorRouteChildren {
  AuthenticatedDoctorCaseIdRoute: typeof AuthenticatedDoctorCaseIdRoute
}

const AuthenticatedDoctorRouteChildren: AuthenticatedDoctorRouteChildren = {
  AuthenticatedDoctorCaseIdRoute: AuthenticatedDoctorCaseIdRoute,
}

const AuthenticatedDoctorRouteWithChildren =
  AuthenticatedDoctorRoute._addFileChildren(AuthenticatedDoctorRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedDoctorRoute: typeof AuthenticatedDoctorRouteWithChildren
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedConsultationIdRoute: typeof AuthenticatedConsultationIdRoute
  AuthenticatedDoctorsIdRoute: typeof AuthenticatedDoctorsIdRoute
  AuthenticatedIntakeIdRoute: typeof AuthenticatedIntakeIdRoute
  AuthenticatedPaymentIdRoute: typeof AuthenticatedPaymentIdRoute
  AuthenticatedReviewIdRoute: typeof AuthenticatedReviewIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDoctorRoute: AuthenticatedDoctorRouteWithChildren,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedConsultationIdRoute: AuthenticatedConsultationIdRoute,
  AuthenticatedDoctorsIdRoute: AuthenticatedDoctorsIdRoute,
  AuthenticatedIntakeIdRoute: AuthenticatedIntakeIdRoute,
  AuthenticatedPaymentIdRoute: AuthenticatedPaymentIdRoute,
  AuthenticatedReviewIdRoute: AuthenticatedReviewIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  StartRoute: StartRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
